### ISSUE TITLE
update window.Typo3Neos API

### ISSUE THREAD

**Issue by mhsdesign** [sandstorm/MxGraph#22]
i just had a look at this pr https://github.com/neos/neos-development-collection/pull/3656 and it reminded me that this package still used the outdated api:
https://github.com/sandstorm/MxGraph/blob/652bc1d3a3f3955d3dc0be70bdb4b57576f484a0/Resources/Private/Templates/DiagramEditor/Index.html#L89

**Comment by skurfuerst** [comment]
ah good point :) Yeah we should definitely fix it :D

**Comment by markusguenther** [comment]
But we have no API for the content reload. So, that will be then a more native JS based replace.
<img width="595" alt="Screenshot 2023-03-03 at 09 28 05" src="https://user-images.githubusercontent.com/1014126/222670338-9e5f677e-2250-4831-8705-8f48bfa6dfe6.png">

**Comment by skurfuerst** [comment]
This is fixed by now with v3 :)
